_format_version: "2.1"
_transform: true

plugins:
  - name: custom-auth

services:
  - name: service
    url: http://service:9820
    routes:
      - name: expense-route
        paths:
          - /expense/v1
        strip_path: false
        preserve_host: false
    plugins:
      - name: custom-auth
        config:
          auth_service_url: "http://expensetracker:9898/auth/v1/ping"
  
  - name: ds-service
    url: http://ds-service:8010
    routes:
      - name: ds-route
        paths:
          - /v1/ds
        strip_path: false
        preserve_host: false
    plugins:
      - name: custom-auth
        config:
          auth_service_url: "http://expensetracker:9898/auth/v1/ping"

  - name: user-service
    url: http://user-service:9810
    routes:
      - name: user-route
        paths:
          - /user/v1
        strip_path: false
        preserve_host: false
    plugins:
      - name: custom-auth
        config:
          auth_service_url: "http://expensetracker:9898/auth/v1/ping"

  - name: expensetracker
    url: http://expensetracker:9898
    routes:
      - name: auth-route
        paths:
          - /auth/v1
        strip_path: false
        preserve_host: false